[package]
name = "inherent"
version = "0.1.3" # remember to update number in readme for major versions
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Make trait methods callable without the trait in scope"
repository = "https://github.com/dtolnay/inherent"
documentation = "https://docs.rs/inherent"
readme = "README.md"

[lib]
proc-macro = true

[badges]
travis-ci = { repository = "dtolnay/inherent" }

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
rustversion = "1.0"
trybuild = { version = "1.0.19", features = ["diff"] }
